#!/bin/sh
# Emulate the mplayer hearbeat-cmd to keep xscreensaver from coming on while the kodi gui is active.
# Inspiration from this post: http://ubuntuforums.org/showthread.php?t=1931074&p=11716198#post11716198

# Nothing to do if user does not have requisite binaries.
[ -z $(which xscreensaver-command) ] && exit 1

while sleep 49; do
   if [ -n "$(pgrep kodi)" ]; then
      xscreensaver-command -deactivate > /dev/null 2>&1
   fi
done
